name: Protobuf Build and Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1.34.0

      - name: Verify Buf installation
        run: buf --version

      - name: Lint Protobuf with Buf
        run: buf lint

      - name: Build Protobuf with Buf
        run: buf build

      - name: Generate clients code with Buf
        run: buf generate
